name: dart_http_server_runtime
description: Rust-backed HTTP server runtime for Dart HTTP.
version: 0.3.44
publish_to: "https://pub.hippolabs.org"
repository: https://github.com/hippolabs-org/dart-http/tree/main/packages/dart_http_server_runtime

environment:
  sdk: ">=3.13.0 <4.0.0"

resolution: workspace

dependencies:
  dart_http_core:
    hosted: "https://pub.hippolabs.org"
    version: ^0.3.49
  ffi: ^2.2.0
  hippolabs_native_assets:
    hosted: "https://pub.hippolabs.org"
    version: ^0.1.2
  hooks: ^2.0.2
  json_schema:
    hosted: https://pub.hippolabs.org
    version: ^0.1.2
  native_exchange:
    hosted: "https://pub.hippolabs.org"
    version: ^0.3.0

dev_dependencies:
  ffigen: ^20.1.1
  test: ^1.30.0
