// Generated by package:ffigen. Do not edit.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:dart_http_native_client/dart_http_native_client.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int32 Function()>()
external int dart_http_native_client_abi_version();

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int64)>()
external bool dart_http_native_client_cancel(int client_id, int request_id);

@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void dart_http_native_client_close(int client_id);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Int64)>()
external int dart_http_native_client_create(
  int completion_port,
  int websocket_connect_timeout_ms,
  int request_timeout_ms,
);

@ffi.Native<ffi.Int32 Function()>()
external int dart_http_native_client_engine_initialize();

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeHttpResult>)>()
external void dart_http_native_client_free_result(ffi.Pointer<NativeHttpResult> result);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>()
external int dart_http_native_client_initialize_api_dl(ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void dart_http_native_client_response_reader_cancel(ffi.Pointer<ffi.Void> reader);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void dart_http_native_client_response_reader_release(ffi.Pointer<ffi.Void> reader);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Int64)>()
external int dart_http_native_client_response_reader_request_next(
  ffi.Pointer<ffi.Void> reader,
  int request_id,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Int64, ffi.Pointer<ffi.Void>)>()
external int dart_http_native_client_response_reader_take(
  ffi.Pointer<ffi.Void> reader,
  int request_id,
  ffi.Pointer<ffi.Void> out_buffer,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<NativeHttpResult>, ffi.Pointer<ffi.Void>)>()
external bool dart_http_native_client_result_take_body_buffer(
  ffi.Pointer<NativeHttpResult> result,
  ffi.Pointer<ffi.Void> out_buffer,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Int64,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<NativeHttpHeader>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Void>,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Int32,
    ffi.Int32,
  )
>()
external int dart_http_native_client_start(
  int client_id,
  ffi.Pointer<ffi.Char> method,
  ffi.Pointer<ffi.Char> url,
  ffi.Pointer<NativeHttpHeader> headers,
  int header_count,
  ffi.Pointer<ffi.Uint8> body,
  int body_length,
  int dart_upload_id,
  int dart_upload_length,
  ffi.Pointer<ffi.Void> native_buffer,
  ffi.Pointer<ffi.Void> native_body,
  int native_body_length,
  ffi.Pointer<ffi.Uint8> native_prefix,
  int native_prefix_length,
  ffi.Pointer<ffi.Uint8> native_suffix,
  int native_suffix_length,
  int redirect_policy,
  int response_mode,
);

@ffi.Native<ffi.Pointer<NativeHttpResult> Function(ffi.Int64, ffi.Int64)>()
external ffi.Pointer<NativeHttpResult> dart_http_native_client_take_result(
  int client_id,
  int request_id,
);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.IntPtr)>()
external ffi.Pointer<ffi.Uint8> dart_http_native_client_upload_chunk_allocate(int length);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int64)>()
external bool dart_http_native_client_upload_close(int client_id, int upload_id);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.IntPtr)>()
external int dart_http_native_client_upload_create(
  int client_id,
  int completion_port,
  int capacity,
);

@ffi.Native<
  ffi.Int32 Function(ffi.Int64, ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Uint8>, ffi.IntPtr)
>()
external int dart_http_native_client_upload_write(
  int client_id,
  int upload_id,
  int write_id,
  ffi.Pointer<ffi.Uint8> bytes,
  int length,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int64)>()
external bool dart_http_native_client_websocket_abort(int client_id, int socket_id);

@ffi.Native<ffi.Int32 Function(ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Void>)>()
external int dart_http_native_client_websocket_adopt_byte_stream(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Void> native_stream,
);

@ffi.Native<
  ffi.Bool Function(ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Uint64>, ffi.Pointer<ffi.Uint64>)
>()
external bool dart_http_native_client_websocket_byte_stream_stats(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint64> chunk_count,
  ffi.Pointer<ffi.Uint64> byte_count,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Int32, ffi.Pointer<ffi.Char>)>()
external int dart_http_native_client_websocket_close(
  int client_id,
  int socket_id,
  int code,
  ffi.Pointer<ffi.Char> reason,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int64)>()
external bool dart_http_native_client_websocket_close_byte_stream(int client_id, int socket_id);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Int64,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<NativeHttpHeader>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.IntPtr,
    ffi.IntPtr,
    ffi.IntPtr,
    ffi.Int64,
    ffi.Int64,
  )
>()
external int dart_http_native_client_websocket_connect(
  int client_id,
  ffi.Pointer<ffi.Char> url,
  ffi.Pointer<NativeHttpHeader> headers,
  int header_count,
  ffi.Pointer<ffi.Pointer<ffi.Char>> protocols,
  int protocol_count,
  int incoming_capacity,
  int outgoing_capacity,
  int keep_alive_interval_ms,
  int keep_alive_timeout_ms,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Uint8>, ffi.IntPtr)>()
external int dart_http_native_client_websocket_drain_and_send_binary(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> message,
  int message_length,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64)>()
external int dart_http_native_client_websocket_drain_byte_stream(int client_id, int socket_id);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Void>,
  )
>()
external int dart_http_native_client_websocket_enqueue_binary_native_prefixed(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> prefix,
  int prefix_length,
  ffi.Pointer<ffi.Void> native_buffer,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Void>,
    ffi.IntPtr,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external int dart_http_native_client_websocket_enqueue_text_base64_native(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> prefix,
  int prefix_length,
  ffi.Pointer<ffi.Void> native_buffer,
  int offset,
  int length,
  ffi.Pointer<ffi.Uint8> suffix,
  int suffix_length,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<NativeWebSocketEvent>, ffi.Pointer<ffi.Void>)>()
external bool dart_http_native_client_websocket_event_take_binary(
  ffi.Pointer<NativeWebSocketEvent> event,
  ffi.Pointer<ffi.Void> out_buffer,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64)>()
external int dart_http_native_client_websocket_flush(int client_id, int socket_id);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebSocketEvent>)>()
external void dart_http_native_client_websocket_free_event(ffi.Pointer<NativeWebSocketEvent> event);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64)>()
external int dart_http_native_client_websocket_pause_byte_stream(int client_id, int socket_id);

@ffi.Native<
  ffi.Bool Function(
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external bool dart_http_native_client_websocket_resume_base64_text_stream(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> prefix,
  int prefix_length,
  ffi.Pointer<ffi.Uint8> suffix,
  int suffix_length,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.IntPtr,
    ffi.IntPtr,
    ffi.IntPtr,
  )
>()
external bool dart_http_native_client_websocket_resume_byte_stream(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> prefix,
  int prefix_length,
  int sequence_offset,
  int payload_unit_count_offset,
  int bytes_per_payload_unit,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Uint8>, ffi.IntPtr)>()
external int dart_http_native_client_websocket_send_binary(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> value,
  int length,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Void>,
  )
>()
external int dart_http_native_client_websocket_send_binary_native_prefixed(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> prefix,
  int prefix_length,
  ffi.Pointer<ffi.Void> native_buffer,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int64, ffi.Pointer<ffi.Char>)>()
external int dart_http_native_client_websocket_send_text(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Char> value,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Void>,
    ffi.IntPtr,
    ffi.IntPtr,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external int dart_http_native_client_websocket_send_text_base64_native(
  int client_id,
  int socket_id,
  ffi.Pointer<ffi.Uint8> prefix,
  int prefix_length,
  ffi.Pointer<ffi.Void> native_buffer,
  int offset,
  int length,
  ffi.Pointer<ffi.Uint8> suffix,
  int suffix_length,
);

@ffi.Native<ffi.Pointer<NativeWebSocketEvent> Function(ffi.Int64, ffi.Int64, ffi.Int32)>()
external ffi.Pointer<NativeWebSocketEvent> dart_http_native_client_websocket_take_event(
  int client_id,
  int socket_id,
  int kind,
);

final class NativeHttpHeader extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> value;

  static ffi.Pointer<NativeHttpHeader> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> name,
    required ffi.Pointer<ffi.Char> value,
  }) => $allocator<NativeHttpHeader>()
    ..ref.name = name
    ..ref.value = value;
}

final class NativeHttpResult extends ffi.Struct {
  @ffi.Bool()
  external bool success;

  @ffi.Int32()
  external int status_code;

  external ffi.Pointer<NativeHttpHeader> headers;

  @ffi.IntPtr()
  external int header_count;

  external ffi.Pointer<ffi.Void> body_stream;

  external ffi.Pointer<ffi.Void> body_reader;

  @ffi.Int64()
  external int body_reader_id;

  external ffi.Pointer<ffi.Void> body_buffer;

  external ffi.Pointer<ffi.Char> error;

  static ffi.Pointer<NativeHttpResult> $allocate(
    ffi.Allocator $allocator, {
    required bool success,
    required int status_code,
    required ffi.Pointer<NativeHttpHeader> headers,
    required int header_count,
    required ffi.Pointer<ffi.Void> body_stream,
    required ffi.Pointer<ffi.Void> body_reader,
    required int body_reader_id,
    required ffi.Pointer<ffi.Void> body_buffer,
    required ffi.Pointer<ffi.Char> error,
  }) => $allocator<NativeHttpResult>()
    ..ref.success = success
    ..ref.status_code = status_code
    ..ref.headers = headers
    ..ref.header_count = header_count
    ..ref.body_stream = body_stream
    ..ref.body_reader = body_reader
    ..ref.body_reader_id = body_reader_id
    ..ref.body_buffer = body_buffer
    ..ref.error = error;
}

final class NativeWebSocketEvent extends ffi.Struct {
  @ffi.Int32()
  external int kind;

  @ffi.Int64()
  external int socket_id;

  @ffi.Int64()
  external int operation_id;

  @ffi.Int32()
  external int close_code;

  external ffi.Pointer<ffi.Char> text;

  external ffi.Pointer<ffi.Void> binary_buffer;

  static ffi.Pointer<NativeWebSocketEvent> $allocate(
    ffi.Allocator $allocator, {
    required int kind,
    required int socket_id,
    required int operation_id,
    required int close_code,
    required ffi.Pointer<ffi.Char> text,
    required ffi.Pointer<ffi.Void> binary_buffer,
  }) => $allocator<NativeWebSocketEvent>()
    ..ref.kind = kind
    ..ref.socket_id = socket_id
    ..ref.operation_id = operation_id
    ..ref.close_code = close_code
    ..ref.text = text
    ..ref.binary_buffer = binary_buffer;
}
